config/routes.rb
Rails.application.routes.draw do
  resources :quiz_answers
  resources :quiz_questions
  resources :quizzes
  resources :words
  resources :topics
  resources :courses
  resources :categories
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/signup',       to: 'users#new',            via: 'get'
  match '/signin',       to: 'sessions#new',         via: 'get'
  match '/signout',      to: 'sessions#destroy',     via: 'delete'
  match '/help',         to: 'static_pages#help',    via: 'get'
  match '/about',        to: 'static_pages#about',   via: 'get'
  match '/contact',      to: 'static_pages#contact', via: 'get'
  match '/user/courses', to: 'users#courses',        via: 'get'
end

app/models/quiz_answer.rb
class QuizAnswer < ApplicationRecord
  belongs_to :quiz_question
end

app/controllers/quiz_answers_controller.rb
class QuizAnswersController < ApplicationController
  before_action :set_quiz_answer, only: [:show, :edit, :update, :destroy]

  # GET /quiz_answers
  # GET /quiz_answers.json
  def index
    @quiz_answers = QuizAnswer.all
  end

  # GET /quiz_answers/1
  # GET /quiz_answers/1.json
  def show

  end

  # GET /quiz_answers/new
  def new
    @quiz_answer = QuizAnswer.new
  end

  # GET /quiz_answers/1/edit
  def edit
  end

  # POST /quiz_answers
  # POST /quiz_answers.json
  def create
    @quiz_answer = QuizAnswer.new(quiz_answer_params)

    respond_to do |format|
      if @quiz_answer.save
        format.html { redirect_to @quiz_answer.quiz_question, notice: 'Quiz answer was successfully created.' }
        format.json { render :show, status: :created, location: @quiz_answer }
      else
        format.html { render :new }
        format.json { render json: @quiz_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quiz_answers/1
  # PATCH/PUT /quiz_answers/1.json
  def update
    respond_to do |format|
      if @quiz_answer.update(quiz_answer_params)
        format.html { redirect_to @quiz_answer, notice: 'Quiz answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz_answer }
      else
        format.html { render :edit }
        format.json { render json: @quiz_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quiz_answers/1
  # DELETE /quiz_answers/1.json
  def destroy
    @quiz_answer.destroy
    respond_to do |format|
      format.html { redirect_to quiz_answers_url, notice: 'Quiz answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz_answer
      @quiz_answer = QuizAnswer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_answer_params
      params.require(:quiz_answer).permit(:content, :correct, :quiz_question_id)
    end
end

app/helpers/quiz_answers_helper.rb
module QuizAnswersHelper
end

app/views/quiz_answers/_form.html.erb
<%= form_for(quiz_answer) do |f| %>
  <% if quiz_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz_answer.errors.count, "error") %> prohibited this quiz_answer from being saved:</h2>

      <ul>
      <% quiz_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :correct %>
    <%= f.check_box :correct %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quiz_answers/_quiz_answer.html.erb
<% if quiz_answer.quiz_question.question_type == 'radio' %>
  <div class="radio">
    <label><input type="radio"><%= quiz_answer.content %></label>
  </div>
<% else %>
  <div class="checkbox">
    <label><input type="checkbox"><%= quiz_answer.content %></label>
  </div>
<% end %>

app/views/quiz_answers/edit.html.erb
<h1>Editing Quiz Answer</h1>

<%= render 'form', quiz_answer: @quiz_answer %>

<%= link_to 'Show', @quiz_answer %> |
<%= link_to 'Back', quiz_answers_path %>

app/views/quiz_answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quiz Answers</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Correct</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quiz_answers.each do |quiz_answer| %>
      <tr>
        <td><%= quiz_answer.content %></td>
        <td><%= quiz_answer.correct %></td>
        <td><%= link_to 'Show', quiz_answer %></td>
        <td><%= link_to 'Edit', edit_quiz_answer_path(quiz_answer) %></td>
        <td><%= link_to 'Destroy', quiz_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz Answer', new_quiz_answer_path %>

app/views/quiz_answers/new.html.erb
<h1>New Quiz Answer</h1>

<%= render 'form', quiz_answer: @quiz_answer %>

<%= link_to 'Back', quiz_answers_path %>

app/views/quiz_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @quiz_answer.content %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @quiz_answer.correct %>
</p>

<%= link_to 'Edit', edit_quiz_answer_path(@quiz_answer) %> |
<%= link_to 'Back', quiz_answers_path %>