config/routes.rb
Rails.application.routes.draw do
  resources :quiz_answers
  resources :quiz_questions
  resources :quizzes
  resources :words
  resources :topics
  resources :courses
  resources :categories
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/signup',       to: 'users#new',            via: 'get'
  match '/signin',       to: 'sessions#new',         via: 'get'
  match '/signout',      to: 'sessions#destroy',     via: 'delete'
  match '/help',         to: 'static_pages#help',    via: 'get'
  match '/about',        to: 'static_pages#about',   via: 'get'
  match '/contact',      to: 'static_pages#contact', via: 'get'
  match '/user/courses', to: 'users#courses',        via: 'get'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	
	has_many :courses
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :registrations
  has_many :topics, dependent: :destroy
  has_many :users, through: :registrations
  belongs_to :category
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :quiz_questions
  belongs_to :topic
end

app/models/quiz_answer.rb
class QuizAnswer < ApplicationRecord
  belongs_to :quiz_question
end

app/models/quiz_question.rb
class QuizQuestion < ApplicationRecord
  has_many :quiz_answers
  belongs_to :quiz
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :course
  has_many :words, dependent: :destroy
  has_many :quizzes
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :registrations
  has_many :microposts, dependent: :destroy
  has_many :courses, through: :registrations
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    #Micropost.from_users_followed_by(self)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  def join_course(course)
    registrations.create!(course_id: course.id )
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :topic
end

app/controllers/quiz_questions_controller.rb
class QuizQuestionsController < ApplicationController
  before_action :set_quiz_question, only: [:show, :edit, :update, :destroy]

  # GET /quiz_questions
  # GET /quiz_questions.json
  def index
    @quiz_questions = QuizQuestion.all
  end

  # GET /quiz_questions/1
  # GET /quiz_questions/1.json
  def show
    @quiz_answers =  @quiz_question.quiz_answers

    # Create new question answer instance.
    @quiz_answer = QuizAnswer.new
    @quiz_answer.quiz_question_id = @quiz_question.id
  end

  # GET /quiz_questions/new
  def new
    @quiz_question = QuizQuestion.new(:quiz_question_id => params[:quiz_question].id)
  end

  # GET /quiz_questions/1/edit
  def edit
  end

  # POST /quiz_questions
  # POST /quiz_questions.json
  def create
    @quiz_question = QuizQuestion.new(quiz_question_params)

    respond_to do |format|
      if @quiz_question.save
        format.html { redirect_to @quiz_question, notice: 'Quiz question was successfully created.' }
        format.json { render :show, status: :created, location: @quiz_question }
      else
        format.html { render :new }
        format.json { render json: @quiz_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quiz_questions/1
  # PATCH/PUT /quiz_questions/1.json
  def update
    respond_to do |format|
      if @quiz_question.update(quiz_question_params)
        format.html { redirect_to @quiz_question, notice: 'Quiz question was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz_question }
      else
        format.html { render :edit }
        format.json { render json: @quiz_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quiz_questions/1
  # DELETE /quiz_questions/1.json
  def destroy
    @quiz_question.destroy
    respond_to do |format|
      format.html { redirect_to quiz_questions_url, notice: 'Quiz question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz_question
      @quiz_question = QuizQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_question_params
      params.require(:quiz_question).permit(:name, :description, :question_type, :quiz_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
  def course_author?(course)
    begin
      course.author_id == current_user.id
    rescue
      false
    end
  end
end

app/helpers/quiz_answers_helper.rb
module QuizAnswersHelper
end

app/helpers/quiz_questions_helper.rb
module QuizQuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/quiz_questions/_form.html.erb
<%= form_for(quiz_question) do |f| %>
  <% if quiz_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz_question.errors.count, "error") %> prohibited this quiz_question from being saved:</h2>

      <ul>
      <% quiz_question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :question_type %>
    <%= f.text_field :question_type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quiz_questions/_quiz_question.html.erb
<li class="list-group-item">
   <%= link_to quiz_question.name, quiz_question %>
</li>

app/views/quiz_questions/edit.html.erb
<h1>Editing Quiz Question</h1>

<%= render 'form', quiz_question: @quiz_question %>

<%= link_to 'Show', @quiz_question %> |
<%= link_to 'Back', quiz_questions_path %>

app/views/quiz_questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quiz Questions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quiz_questions.each do |quiz_question| %>
      <tr>
        <td><%= quiz_question.name %></td>
        <td><%= quiz_question.description %></td>
        <td><%= quiz_question.question_type %></td>
        <td><%= link_to 'Show', quiz_question %></td>
        <td><%= link_to 'Edit', edit_quiz_question_path(quiz_question) %></td>
        <td><%= link_to 'Destroy', quiz_question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz Question', new_quiz_question_path %>

app/views/quiz_questions/new.html.erb
<h1>New Quiz Question</h1>

<%= render 'form', quiz_question: @quiz_question %>

<%= link_to 'Back', quiz_questions_path %>

app/views/quiz_questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @quiz_question.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @quiz_question.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @quiz_question.question_type %>
</p>

<%= render "shared/question_answers" %>
<%= render "shared/question_answer_form" %>


<%= link_to 'Edit', edit_quiz_question_path(@quiz_question) %> |
<%= link_to 'Back', quiz_questions_path %>