config/routes.rb
Rails.application.routes.draw do
  resources :quiz_answers
  resources :quiz_questions
  resources :quizzes
  resources :words
  resources :topics
  resources :courses
  resources :categories
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/signup',       to: 'users#new',            via: 'get'
  match '/signin',       to: 'sessions#new',         via: 'get'
  match '/signout',      to: 'sessions#destroy',     via: 'delete'
  match '/help',         to: 'static_pages#help',    via: 'get'
  match '/about',        to: 'static_pages#about',   via: 'get'
  match '/contact',      to: 'static_pages#contact', via: 'get'
  match '/user/courses', to: 'users#courses',        via: 'get'
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :course
  has_many :words, dependent: :destroy
  has_many :quizzes
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user,
                only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @words = @topic.words
    @quizzes = @topic.quizzes
    
    # Build for create new word form.
    @word = Word.new
    @word[:topic_id] = @topic.id
  end

  # GET /topics/new
  def new
    # Get course_id from Url and pass to object model.
    @topic = Topic.new(:course_id => params[:course])
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic.course, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def correct_user
      @topic = Topic.find(params[:id])
      redirect_to(root_url) unless (@topic.course.author_id == current_user.id)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :description, :course_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <%= f.hidden_field :course_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<li class="list-group-item">
   <span class="badge"><%= topic.words.count %> words</span>
   <%= link_to topic.name, topic %>
</li>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.description %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Topic Information</h2>
<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>


<%= render 'shared/challenges' %>

<%= render 'shared/word_form' %>
<%= render 'shared/words'%>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', @topic.course %>