config/routes.rb
Rails.application.routes.draw do
  resources :quiz_answers
  resources :quiz_questions
  resources :quizzes
  resources :words
  resources :topics
  resources :courses
  resources :categories
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/signup',       to: 'users#new',            via: 'get'
  match '/signin',       to: 'sessions#new',         via: 'get'
  match '/signout',      to: 'sessions#destroy',     via: 'delete'
  match '/help',         to: 'static_pages#help',    via: 'get'
  match '/about',        to: 'static_pages#about',   via: 'get'
  match '/contact',      to: 'static_pages#contact', via: 'get'
  match '/user/courses', to: 'users#courses',        via: 'get'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	
	has_many :courses
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :registrations
  has_many :topics, dependent: :destroy
  has_many :users, through: :registrations
  belongs_to :category
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :quiz_questions
  belongs_to :topic
end

app/models/quiz_answer.rb
class QuizAnswer < ApplicationRecord
  belongs_to :quiz_question
end

app/models/quiz_question.rb
class QuizQuestion < ApplicationRecord
  has_many :quiz_answers
  belongs_to :quiz
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :course
  has_many :words, dependent: :destroy
  has_many :quizzes
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :registrations
  has_many :microposts, dependent: :destroy
  has_many :courses, through: :registrations
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    #Micropost.from_users_followed_by(self)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  def join_course(course)
    registrations.create!(course_id: course.id )
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :topic
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
  def course_author?(course)
    begin
      course.author_id == current_user.id
    rescue
      false
    end
  end
end

app/helpers/quiz_answers_helper.rb
module QuizAnswersHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/shared/_categories.html.erb
<h2>All categories</h2>
<ul class="category">
  <%= render @courses %>
</ul>

app/views/shared/_category_course.html.erb
<section class="courses-page">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center pane-header">
        <h2 class="text-uppercase">CATEGORY</h2>
        <div class="divider"></div>
      </div>
      <br/>


      <% @categories.each do |category| %>
      <div class="col-md-4 ">
        <div class="pv-30 ph-20 service-block bordered shadow text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="100">
          <!-- <span class="icon bg-df circle"><i class="fa fa-diamond"></i></span> -->
          
          <a href="/categories/<%= category.id %>">
              <h3><%= category.name %></h3>
            <i class="pl-5 fa fa-angle-double-right"></i>
          </a>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/shared/_challenges.html.erb
<h3>Challenges</h3>


<ul class="topics list-group">
  <%= render @quizzes %>
</ul>

<div style="padding-top: 15px;">
  <%= link_to 'New Challenge', new_quiz_path(:topic => @topic) , {:class => "primary-link"}%>
</div>

<br/>

app/views/shared/_courses.html.erb
<section class="courses-page">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center pane-header">
        <h2 class="text-uppercase">All Courses</h2>
        <div class="divider"></div>
        <h5></h5>
      </div>
      <br/>
      <% @courses.each do |course| %>
      <div class="col-md-4 ">
        <div class="pv-30 ph-20 service-block bordered shadow text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="100">
          <span class="icon bg-df circle"><i class="fa fa-diamond"></i></span>
          <h3><%= course.name %></h3>
          <div class="divider clearfix"></div>
          <p><%= course.description %></p>
          <a href="/courses/<%= course.id %>">Read More <i class="pl-5 fa fa-angle-double-right"></i></a>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_question_answer_form.html.erb
<% unless !course_author?(@quiz_answer.quiz_question.quiz.topic.course) %>
<h2>Add Answer</h2>
  <%= form_for(@quiz_answer) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <%= f.label :content, :class => "control-label" %>
      <%= f.text_field :content, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :correct , :class => "control-label" %>
      <%= f.check_box :correct , :class => "form-control"%>
    </div>

    <%= f.hidden_field  :quiz_question_id %>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/shared/_question_answers.html.erb
<h3>Answers</h3>

<ul class="topics list-group">
  <%= render @quiz_answers %>
</ul>
<br/>

app/views/shared/_question_form.html.erb
<% unless !course_author?(@quiz.topic.course) %>
<h2>Add Questions</h2>
  <%= form_for(@quiz_question) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <%= f.label :name, :class => "control-label" %>
      <%= f.text_field :name, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :description, :class => "control-label" %>
      <%= f.text_field :description, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :question_type , :class => "control-label" %>
      <%= f.text_field :question_type, :class => "form-control"%>
    </div>
    <%= f.hidden_field  :quiz_id %>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/shared/_quiz_questions.html.erb
<h3>Questions</h3>

<ul class="topics list-group">
  <%= render @quiz.quiz_questions %>
</ul>
<br/>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>

app/views/shared/_word_form.html.erb
<% unless !course_author?(@word.topic.course) %>
<h2>Add words</h2>
  <%= form_for(@word) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :name, :class => "control-label" %>
      <%= f.text_field :name, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :description, :class => "control-label" %>
      <%= f.text_field :description, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :content , :class => "control-label" %>
      <%= f.text_field :content, :class => "form-control"%>
    </div>
    <%= f.hidden_field :topic_id %>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/shared/_words.html.erb
<h2>All words</h2>
<ul class="course">
  <%= render @words %>
</ul>